// <auto-generated />
namespace DribblyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedForeignKeyConstraintOnPlayerGame_GameTeam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedForeignKeyConstraintOnPlayerGame_GameTeam));
        
        string IMigrationMetadata.Id
        {
            get { return "201710060706357_AddedForeignKeyConstraintOnPlayerGame_GameTeam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
